### PR TITLE
Patch exiles 1.1 - api status & fix restart PPPP on failure

### PR DESCRIPTION
**Pull request by sondregronas**
Needs some work & testing, but I noticed pppp-state will only raise a warning when pppp connection is lost, however a restart is warranted whenever this happens (reloading / attempts at reconnecting seem to always fail). 

With this PR the application will crash  when this happens. If running via docker this should/could restart, but I'm sure there's a more graceful approach to do this.

Timeouts on attempts to send gcode should probably warrant this behavior as well, but I'll test some more when I have the time.

EDIT: I have reworked this to just restart the PPPPService, seems to work fine for now. Will remove draft once properly monitored/tested

### CODE REVIEW

**Comment by sondregronas** [comment]
I've got a working version where PPPP will no longer fail to start up after a while, but there is an underlying issue I can't wrap my head around. After around 3-4 hours, the PPPP will start to get corrupted (it will look fine up until this point). I am unable to pinpoint where it's failing

```bash
ankerctl  | [E] 192.168.200.20 - - [10/Jul/2024 13:50:29] code 400, message Bad request syntax ('\x88\x82B\x1aÃ¼Aò')
ankerctl  | [E] 192.168.200.20 - - [10/Jul/2024 13:50:49] code 400, message Bad request syntax ('\x88\x82\x03Yo´\x00±')
ankerctl  | [E] 192.168.200.20 - - [10/Jul/2024 13:50:53] code 400, message Bad request syntax ('\x88\x82\x1aC~V\x19«')
ankerctl  | [E] 192.168.200.20 - - [10/Jul/2024 13:50:57] code 400, message Bad request syntax ('\x88\x82àÂäõã*')
ankerctl  | [E] 192.168.200.20 - - [10/Jul/2024 13:51:01] code 400, message Bad request syntax ('\x88\x82Aö\x94AB\x1e')
ankerctl  | [E] 192.168.200.20 - - [10/Jul/2024 13:51:09] code 400, message Bad HTTP/0.9 request type ('\x88\x82Õý')
ankerctl  | [E] 192.168.200.20 - - [10/Jul/2024 13:51:17] code 400, message Bad request syntax ('\x88\x827íÝX4\x05')
ankerctl  | [E] 192.168.200.20 - - [10/Jul/2024 13:51:29] code 400, message Bad HTTP/0.9 request type ('\x88\x82¦Æ')
ankerctl  | [E] 192.168.200.20 - - [10/Jul/2024 13:51:41] code 400, message Bad HTTP/0.9 request type ('\x88\x82h')
ankerctl  | [E] 192.168.200.20 - - [10/Jul/2024 13:51:49] code 400, message Bad request syntax ('\x88\x82ý\x8c\x02Õþd')
ankerctl  | [E] 192.168.200.20 - - [10/Jul/2024 13:51:57] code 400, message Bad request syntax ('\x88\x826;\x9e,5Ó')
ankerctl  | [E] 192.168.200.20 - - [10/Jul/2024 13:52:05] code 400, message Bad request syntax ('\x88\x82¯$Ì>¬Ì')
ankerctl  | [E] 192.168.200.20 - - [10/Jul/2024 13:52:09] code 400, message Bad request syntax ('\x88\x82ß¢\x8a\x01ÜJ')
ankerctl  | [E] 192.168.200.20 - - [10/Jul/2024 13:52:28] code 400, message Bad request syntax ('\x88\x82±\x81\x96\x84²i')
ankerctl  | [E] 192.168.200.20 - - [10/Jul/2024 13:52:39] code 400, message Bad HTTP/0.9 request type ('\x88\x82&±')
```


https://github.com/anselor/ankermake-m5-protocol/assets/44143748/a1c6749e-f1a7-4726-ab25-94dbc1a7855a

image


PPPP works and I get video, but it does not look right. There are a lot of I-frames that render correctly, but it seems all other frames are desyncing (PPPP is also blinking green/red). Sending GCode works at least (_though it might take a couple attempts_).

Scheduling ankerctl to restart every 2hrs should keep it stable, but my guess is that flask_sock acts up. I'll try running ankerctl via gunicorn and test some more, but at least it's _functional_ now.

EDIT:
Updating the dependencies did in fact not help with the data corruption that happens after ~3 hours, but at least sending gcode doesn't break. I've set a cron job to restart the container every 2 hours and this should be really stable. I can't see myself making any more changes.

Again just let me know if I should change this to target the main repo instead of your PR - it just seemed like the most up-to-date version.

**Comment by anselor** [comment]
I merged before I caught that the target was exiles-1.1. Can you submit this again against the exiles branch?

I don't think I ever got the exiles branch and the 1.1 changes synced up because I couldn't get a clear answer as to whether the 1.1 branch changes were anywhere near ready.

**Comment by sondregronas** [comment]
Do you want me to open a PR with just these commits, or everything? The PR is based on exiles-1.1, I've only tested the webserver

EDIT: I'll do some quick tests and open a new PR.

**Comment by anselor** [comment]
Just your changes. I was never able to get a clear answer about the state of the 1.1 branch so I haven't messed with it.

**Pull request merged**
